# Generated by Django 6.0.3 on 2026-03-31 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Платная подписка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='Файл трека')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Обложка')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='pc_store.artist')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
