# Generated by Django 6.0.3 on 2026-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(default='Rock', max_length=50, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='track',
            name='plays',
            field=models.PositiveIntegerField(default=0, verbose_name='Прослушивания'),
        ),
    ]
