# Generated by Django 6.0.3 on 2026-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_store', '0002_listeninghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный релиз'),
        ),
    ]
