# Generated by Django 6.0.3 on 2026-04-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_store', '0003_alter_album_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка альбома'),
        ),
    ]
